blank_issues_enabled: false
contact_links:
  - name: "General discussion / help"
    url: "https://github.com/MrLongNight/VjMapper/discussions"
    about: "Discussions, questions and community support"
